EPS = 1e-12

PARAM_V = 400
PARAM_D = 2
PARAM_NOISE_STDS = [0.000]
PARAM_PERTURBS = [10.0]
PARAM_SAMPLINGS = [2.5]
PARAM_DIST_THRESHOLD = 3.5

STRESS_SAMPLE = 'global' # global | semilocal | local
USE_SPARSE_EIG = False
USE_SPARSE_SVD = True

KERNEL_SAMPLES = 16 # Helps a lot going from 2 to 16 for noise cases, was 16
ORTHO_SAMPLES = True # Helps a lot (reduce mean error by 2 times)
MULT_NOISE = False
EXACT_LOCAL_STRESS = False
SS_SAMPLES = 60
WEIGHT_KERNEL_SAMPLE = False

K_RING = 3

CONSOLIDATE_READ_FROM_CACHE = True
CONSOLIDATE_WRITE_TO_CACHE = True

STRESS_VAL_PERC = 0

TOP_STRESS_KERNEL = 8

MAX_EDGE_LEN_IN_METER = 30.0
METER_RATIO = 0
MAX_NEIGHBORS = 8

MIN_LOCAL_NBHD = 30

PLOT_AFFINE_FIT = False

FLOOR_PLAN_FN = "space.xml?10-2"
DIR_PLOT = "plot"
DIR_DATA = "data"
DIR_BIN = "bin"
DIR_TMP = "tmp"
DIR_CACHE = "cache"
